### ISSUE TITLE
Add link in the Readme file to go download the app on the App Store

### ISSUE THREAD

**Issue by narFnarF** [owncloud/notes-iOS-App#53]
Currently, the readme file provides no link to go download the app in the App Store. It would be convenient to have it.

Nextcloud currently links to this github project everywhere they suggest to go download the iOS Notes app, but the user gets here and doesn't know where to go next. Having the link would help them go to their goal (getting the app!)

**Comment by narFnarF** [comment]
I think the link would be this: https://apps.apple.com/fr/app/cloudnotes-owncloud-notes/id813973264

**Comment by fireheadman** [comment]
Guessing there isn't much push to support this... and only mention it in a half-arsed way.
I got here also and was confused.

Since most of the Nextcloud devs are from the OwnCloud pool maybe they will pick this up and support it more mainstream????

**Comment by DeepDiver1975** [comment]
> Guessing there isn't much push to support this

The author of this app is Peter Hedlund - he is still activly maintaining this app.
So I don't see any lack of support or something ...



>  No way I would pay for an app like this knowing it isn't given proper attention out the gate.

What would be your expectation? I don't understand your comment. THX

**Comment by fireheadman** [comment]
I find it odd that "NextCloud" made "Notes" and official app.   Nextcloud is free to use, however this app is requiring users to pay for it in order to use the free notes app in nextcloud.   I understand devs like to be compensated for their work, but how come Nextcloud is not sponsoring the dev and helping make this app be all inclusively free as the app is?
